#!/bin/sh -e

ISODIR=$(mktemp -d)

cargo xbuild --target i686.json --release
cd target/i686/release
nasm -f elf -o start.o ../../../start.asm
ld -m elf_i386 -T ../../../linker.ld -o kernel start.o libsnake.a --gc-sections

mkdir -p "$ISODIR/boot/grub"
cp kernel "$ISODIR/boot/kernel"
echo 'menuentry "SNAKE" { multiboot2 /boot/kernel }' > "$ISODIR/boot/grub/grub.cfg"
grub-mkrescue "$ISODIR" -o "$ISODIR/disk.iso"

qemu-system-x86_64 -cdrom "$ISODIR/disk.iso"

rm -r $ISODIR
